### ISSUE TITLE
Early un-escape of \

### ISSUE THREAD

**Issue by bwmilby** [Ferruslogic/PhotonJSON#2]
https://github.com/Ferruslogic/PhotonJSON/blob/6563d62c3c7c0ee4e6264d3638d3e5fe037891ed/PhotonJSON.livecodescript#L233

If un-escaped here, then there is a possibility of converting `\\n` or `\\t` improperly for example since the `\\` will be changed to `\`.  Suggest placing it before or inside the `_unicodeEscapes` function but the existence of `\\u` will still need to be considered.

**Comment by torocruzand** [comment]
Thanks a lot. This problem is already solved in Bob Hall's FastJSON library. So I brought that part of the code over here and adapted it. Using the ECMA-404 standard, we have that ```\\ n``` is the string ```\ n```.

**Comment by bwmilby** [comment]
Glad to help out.
